In [ ]:
#!python -m spacy download en_core_web_md

In [ ]:
#import spacy

In [ ]:
#embedding_file=spacy.load('en_core_web_md')

In [ ]:
#embedding_file('want').vector.shape

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from nltk.tokenize import word_tokenize,sent_tokenize
from sklearn.decomposition import PCA
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

In [ ]:
#!pip install nlp

In [ ]:
#from nlp import load_dataset
from nltk.tokenize import word_tokenize,sent_tokenize

In [ ]:
word_tokenize("Today is a great day!")

['Today', 'is', 'a', 'great', 'day', '!']

In [ ]:
import numpy as np
import tensorflow as tf

In [ ]:
import nltk
import math
import json
import tensorflow_hub as hub
import spacy

In [ ]:
nltk.download('punkt')
nltk.download('gutenberg')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package gutenberg to /root/nltk_data...
[nltk_data]   Unzipping corpora/gutenberg.zip.


True

In [ ]:
from tensorflow.keras.layers import SimpleRNN,GRU,LSTM,Dense,Embedding,InputLayer,Input
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.metrics import CategoricalCrossentropy
from tensorflow.keras.losses import CategoricalCrossentropy,categorical_crossentropy
from tensorflow.keras import Model
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from nltk.corpus import gutenberg

In [ ]:
"""data=open("/content/drive/MyDrive/PhD/Data Sources/WhatsApp/corpus.txt")
data=data.read()"""

'data=open("/content/drive/MyDrive/PhD/Data Sources/WhatsApp/corpus.txt")\ndata=data.read()'

In [ ]:
data=open("0001a.txt")
data=data.read()

# New section

In [ ]:
data

"Racism is still a problem within our society today, and many ethnic minorities face inequalities in many areas, including education, housing, and employment. Ethnic minorities are concentrated into certain areas of the job market, such as manufacture and communication (Brown, 1992), are most likely to be the victims of assault (Abercrombie et al, 1994), and recent surveys have shown that racist ideas still exist in society. This can be seen in a survey, carried out in 1993, that asked a white sample whether they agreed or disagreed with the statement: 'Immigration has enriched the quality of life in Britain' and nearly half of the sample disagreed (Abercrombie et al, 1994, p255). In this essay I will look at what racism is, and how it is defined in contemporary society, and I will then explore why it still persists. In this section I will cover three areas that I think have contributed to the continued existence of racism; culture, economy and politics, all of which have meant that ra

In [ ]:
corpus_list=[]
corpus=sent_tokenize(data)
for sent in corpus:
  corpus_list.append([sent])

In [ ]:
corpus

['Racism is still a problem within our society today, and many ethnic minorities face inequalities in many areas, including education, housing, and employment.',
 'Ethnic minorities are concentrated into certain areas of the job market, such as manufacture and communication (Brown, 1992), are most likely to be the victims of assault (Abercrombie et al, 1994), and recent surveys have shown that racist ideas still exist in society.',
 "This can be seen in a survey, carried out in 1993, that asked a white sample whether they agreed or disagreed with the statement: 'Immigration has enriched the quality of life in Britain' and nearly half of the sample disagreed (Abercrombie et al, 1994, p255).",
 'In this essay I will look at what racism is, and how it is defined in contemporary society, and I will then explore why it still persists.',
 'In this section I will cover three areas that I think have contributed to the continued existence of racism; culture, economy and politics, all of which h

In [ ]:
len(corpus_list)

48

In [ ]:
vectorizer = TfidfVectorizer()

In [ ]:
X = vectorizer.fit_transform(corpus)

In [ ]:
X.shape

(48, 459)

In [ ]:
vocab=vectorizer.get_feature_names_out()

In [ ]:
vocab[100]

'consider'

In [ ]:
len(vocab)

459

In [ ]:
embeddings_array=X.toarray().T

In [ ]:
embeddings_array[100]

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.31038711, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        ])

In [ ]:
pca=PCA(n_components=10)

In [ ]:
dense_embeddings=pca.fit_transform(embeddings_array)

In [ ]:
embeddings_dict={}

In [ ]:
for i in range(len(vocab)):
  embeddings_dict[vocab[i]]=dense_embeddings[i].tolist()

In [ ]:
seq_len=10
tokenizer=Tokenizer()
tokenizer.fit_on_texts([data])
x=tokenizer.texts_to_sequences([data])
#x

In [ ]:
x[0]

[8,
 10,
 17,
 7,
 69,
 90,
 53,
 11,
 49,
 2,
 54,
 41,
 42,
 218,
 219,
 4,
 54,
 70,
 136,
 220,
 137,
 2,
 221,
 41,
 42,
 12,
 222,
 55,
 91,
 70,
 3,
 1,
 223,
 71,
 138,
 6,
 224,
 2,
 225,
 92,
 93,
 12,
 226,
 227,
 9,
 24,
 1,
 228,
 3,
 229,
 139,
 140,
 141,
 142,
 2,
 230,
 231,
 22,
 232,
 5,
 33,
 14,
 17,
 143,
 4,
 11,
 13,
 50,
 24,
 72,
 4,
 7,
 233,
 144,
 73,
 4,
 234,
 5,
 235,
 7,
 34,
 145,
 236,
 25,
 237,
 146,
 147,
 18,
 1,
 238,
 239,
 27,
 240,
 1,
 241,
 3,
 242,
 4,
 243,
 2,
 244,
 245,
 3,
 1,
 145,
 147,
 139,
 140,
 141,
 142,
 246,
 4,
 13,
 148,
 35,
 43,
 149,
 44,
 150,
 8,
 10,
 2,
 247,
 15,
 10,
 94,
 4,
 56,
 11,
 2,
 35,
 43,
 151,
 248,
 74,
 15,
 17,
 75,
 4,
 13,
 249,
 35,
 43,
 250,
 152,
 70,
 5,
 35,
 251,
 22,
 252,
 9,
 1,
 153,
 253,
 3,
 8,
 57,
 58,
 2,
 95,
 154,
 3,
 45,
 22,
 254,
 5,
 8,
 10,
 46,
 155,
 2,
 255,
 76,
 3,
 53,
 11,
 51,
 35,
 43,
 47,
 24,
 256,
 44,
 257,
 146,
 258,
 259,
 3,
 8,
 260,
 261,
 7,
 262,
 156,

In [ ]:
len(x[0])

1555

In [ ]:
#tokenizer.get_config()

In [ ]:
vocab_dict=json.loads(tokenizer.get_config().get('word_index'))

In [ ]:
vocab_dict

{"'immigration": 239,
 "'other'": 30,
 "'reserve": 199,
 "'the": 291,
 '1950s': 210,
 '1960s': 423,
 '1962': 424,
 '1968': 299,
 '1970s': 429,
 '1978': 271,
 '1979': 440,
 '1987': 282,
 '1989': 19,
 '1992': 93,
 '1993': 234,
 '1994': 142,
 '1999': 82,
 '2004': 395,
 'a': 7,
 'abercrombie': 139,
 'abilities': 382,
 'abnormal': 330,
 'according': 454,
 'acknowledges': 301,
 'act': 426,
 'action': 302,
 'actions': 109,
 'after': 439,
 'again': 443,
 'agreed': 237,
 'al': 141,
 'all': 154,
 'along': 389,
 'also': 38,
 'although': 116,
 'an': 46,
 'and': 2,
 'apparent': 122,
 'are': 12,
 'areas': 70,
 'argue': 290,
 'argued': 187,
 'argues': 265,
 'army': 88,
 'around': 347,
 'as': 6,
 'asked': 235,
 'assault': 229,
 'associated': 117,
 'asylum': 449,
 'at': 44,
 'automatically': 344,
 'banton': 281,
 'barbaric': 333,
 'be': 24,
 'been': 62,
 'before': 371,
 'began': 415,
 'behaviour': 418,
 'belief': 101,
 'beliefs': 79,
 'between': 467,
 'black': 211,
 'both': 66,
 'bought': 431,
 'britai

In [ ]:
vals=list(vocab_dict.values())
keys=list(vocab_dict.keys())
#keys[vals.index(1)]

In [ ]:
vocab_size=len(keys)

In [ ]:
vocab_size

469

In [ ]:
embedding_array=np.zeros((vocab_size+1,300))
embedding_array.shape

(470, 300)

In [ ]:
"""for word,i in tokenizer.word_index.items():
  if word in embeddings_dict:
    embedding_vector=embeddings_dict[word]
  #if embedding_vector is not None:
    embedding_array[i]=embedding_vector"""

'for word,i in tokenizer.word_index.items():\n  if word in embeddings_dict:\n    embedding_vector=embeddings_dict[word]\n  #if embedding_vector is not None:\n    embedding_array[i]=embedding_vector'

In [ ]:
for word,i in tokenizer.word_index.items():
  embedding_vector=embedding_file(word).vector
  if embedding_vector is not None:
    embedding_array[i]=embedding_vector

NameError: ignored

In [ ]:
#embedding_array[7306]

In [ ]:
len(x[0])

161101

In [ ]:
x[0][0:15]

[32, 45, 92, 4410, 4411, 2794, 5, 346, 5, 32, 96, 493, 633, 3, 1024]

In [ ]:
inner_list=[]
X={}
corpus_length=len(x[0])-seq_len
k=0

for i in range(0,corpus_length,seq_len):
  inner_list.clear()
  for j in range(i,i+seq_len):
    inner_list.append(x[0][j])
  X[k]=inner_list[:]
  k=k+1

In [ ]:
#list(X.values())
x_train=[]
y_train=[]
for it in list(X.values()):
  x_train.append(it[0:-1])
  y_train.append(it[-1])

In [ ]:
x_train[3]

[4, 1551, 3, 17, 675, 1025, 588, 61, 364]

In [ ]:
len(x_train)

16110

In [ ]:
X=np.array(x_train)
#input_seq.shape
y=np.array(y_train).reshape(len(y_train),1)
#target=tf.reshape(tf.constant(y_train),[len(y_train),1])

In [ ]:
y.shape

(16110, 1)

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3)

In [ ]:
X_train.shape

(11277, 9)

In [ ]:
y_train

array([[  25],
       [  12],
       [4296],
       ...,
       [  15],
       [1345],
       [  60]])

In [ ]:
input_seq,test_seq,y_true,y_hat=tf.constant(X_train),tf.constant(X_test),tf.constant(y_train),tf.constant(y_test)

In [ ]:
input_seq

<tf.Tensor: shape=(11277, 9), dtype=int64, numpy=
array([[  15,   84,   12, ...,   25,   96,   53],
       [ 206,    1,   36, ..., 2535,    5,   30],
       [  10, 4295,    2, ...,  647,    4,    2],
       ...,
       [  22,  839,   50, ...,  100,    5,  153],
       [  14, 1113,   45, ...,   22,   28,   24],
       [  13,   60,   12, ...,  528,  630,   13]])>

In [ ]:
y_true

<tf.Tensor: shape=(11277, 1), dtype=int64, numpy=
array([[  25],
       [  12],
       [4296],
       ...,
       [  15],
       [1345],
       [  60]])>

In [ ]:
tf.reduce_max(input_seq)+1

<tf.Tensor: shape=(), dtype=int64, numpy=7232>

In [ ]:
input=Input(shape=(seq_len-1,))
x=Embedding(input_dim=vocab_size+1,input_length=seq_len-1,output_dim=20,trainable=True)(input)
x=LSTM(256,return_sequences=True)(x)
x=LSTM(128,return_sequences=True)(x)
x=LSTM(64)(x)
x=Dense(32)(x)
output=Dense(vocab_size,activation="softmax")(x)
model=Model(input,output)

In [ ]:
model.summary()

In [ ]:
model.compile(optimizer=Adam(0.01),loss=tf.keras.losses.sparse_categorical_crossentropy,metrics=['accuracy'])

In [ ]:
model.fit(input_seq,y_true,epochs=10)

Epoch 1/10
353/353 [==============================] - 13s 23ms/step - loss: 6.7295 - accuracy: 0.0304
Epoch 2/10
353/353 [==============================] - 8s 23ms/step - loss: 6.2491 - accuracy: 0.0308
Epoch 3/10
353/353 [==============================] - 8s 23ms/step - loss: 6.2468 - accuracy: 0.0321
Epoch 4/10
353/353 [==============================] - 8s 23ms/step - loss: 6.2324 - accuracy: 0.0300
Epoch 5/10
353/353 [==============================] - 8s 23ms/step - loss: 6.2279 - accuracy: 0.0269
Epoch 6/10
353/353 [==============================] - 8s 23ms/step - loss: 6.2175 - accuracy: 0.0300
Epoch 7/10
353/353 [==============================] - 8s 23ms/step - loss: 6.2124 - accuracy: 0.0281
Epoch 8/10
353/353 [==============================] - 8s 23ms/step - loss: 6.2273 - accuracy: 0.0278
Epoch 9/10
353/353 [==============================] - 8s 23ms/step - loss: 6.2189 - accuracy: 0.0336
Epoch 10/10
353/353 [==============================] - 8s 23ms/step - loss: 6.2240 - accur

In [ ]:
model.evaluate(test_seq,y_hat)

152/152 [==============================] - 3s 10ms/step - loss: 6.9668 - accuracy: 0.0300


[6.966794013977051, 0.030002068728208542]

In [ ]:
input_text=["she was such a good person"]
#input_text=["he was such a good person and honestly speaking he did make good use of his"]
#input_text=["can you please"]
#input_text=["marriage is such a beautiful"]
toks=tokenizer.texts_to_sequences(input_text)
ins=pad_sequences(toks,maxlen=seq_len-1)
input_tensor=tf.constant(ins)
input_tensor

In [ ]:
pred=model.predict(input_tensor)
keys[vals.index(np.argmax(pred))]

In [ ]:
input_text[0]=input_text[0]+' '+keys[vals.index(np.argmax(pred))]
input_text[0]

In [ ]:
for i in range(10):
  toks=tokenizer.texts_to_sequences(input_text)
  ins=pad_sequences(toks,maxlen=seq_len-1)
  input_tensor=tf.constant(ins)
  pred=model.predict(input_tensor)
  input_text[0]=input_text[0]+' '+keys[vals.index(np.argmax(pred))]

print(input_text)

In [ ]:
sort_pred=np.argsort(pred[0])
pred_words=np.flip(sort_pred[-20:])
for index in pred_words:
  print(keys[vals.index(index)])